<?php
// Checkout hospedado Pagar.me/Stone: somente PIX e cartão.
function pgRequest($config,$method,$path,$payload=null){
    $key=trim((string)$config['pagarme_secret_key']);if($key==='')throw new RuntimeException('Configure a PAGARME_SECRET_KEY no .env.');
    if(!function_exists('curl_init'))throw new RuntimeException('Ative a extensão PHP cURL.');
    $url=rtrim($config['pagarme_base_url'],'/').'/'.ltrim($path,'/');$ch=curl_init($url);
    curl_setopt_array($ch,array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>array('Authorization: Basic '.base64_encode($key.':'),'Accept: application/json','Content-Type: application/json','User-Agent: pagarme-skill-generated/1.0'),CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>30,CURLOPT_FOLLOWLOCATION=>false));
    if($payload!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));
    $raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$error=curl_error($ch);curl_close($ch);
    if($raw===false||$error!=='')throw new RuntimeException('A Pagar.me não respondeu.');$body=json_decode($raw,true);if(!is_array($body))$body=array();return array($status,$body);
}
function pgSchema($db){$db->exec("CREATE TABLE IF NOT EXISTS pagamentos_gateway(id INT UNSIGNED NOT NULL AUTO_INCREMENT,inscricao_id INT UNSIGNED NOT NULL,metodo ENUM('CHECKOUT','PIX','CARD') NOT NULL DEFAULT 'CHECKOUT',payment_link_id VARCHAR(120) NULL,payment_link_url VARCHAR(500) NULL,order_id VARCHAR(120) NULL,referencia_externa VARCHAR(160) NOT NULL,valor DECIMAL(10,2) NOT NULL,status ENUM('PROCESSING','PAID','FAILED','EXPIRED','CANCELLED','REFUNDED') NOT NULL DEFAULT 'PROCESSING',status_gateway VARCHAR(80) NULL,checkout_expira_em DATETIME NULL,confirmado_em DATETIME NULL,email_confirmacao_em DATETIME NULL,erro_tecnico VARCHAR(1000) NULL,criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_pg_inscricao(inscricao_id),UNIQUE KEY uq_pg_link(payment_link_id),KEY idx_pg_referencia(referencia_externa),CONSTRAINT fk_pg_inscricao FOREIGN KEY(inscricao_id) REFERENCES inscricoes(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
function pgLoad($db,$registrationId){$q=$db->prepare('SELECT * FROM pagamentos_gateway WHERE inscricao_id=? LIMIT 1');$q->execute(array($registrationId));return $q->fetch();}
function pgView($p){return array('id'=>(int)$p['id'],'method'=>$p['metodo'],'status'=>$p['status'],'gateway_status'=>$p['status_gateway'],'checkout_url'=>$p['payment_link_url'],'checkout_expires_at'=>$p['checkout_expira_em'],'value_cents'=>(int)round($p['valor']*100));}
function pgCheckoutUrl($url){$p=parse_url($url);if(!$p||strtolower($p['scheme'])!=='https')return false;$h=strtolower($p['host']);return $h==='pagar.me'||substr($h,-9)==='.pagar.me';}
function pgOrderStatus($order){$charge=!empty($order['charges'][0])?$order['charges'][0]:array();$s=strtolower((string)(isset($charge['status'])?$charge['status']:(isset($order['status'])?$order['status']:'')));if(in_array($s,array('paid','captured'),true))return 'PAID';if(in_array($s,array('failed','payment_failed','not_authorized','declined'),true))return 'FAILED';if(in_array($s,array('canceled','cancelled'),true))return 'CANCELLED';if($s==='refunded')return 'REFUNDED';return 'PROCESSING';}
function pgTicket($db,$registrationId){return garantirTicketMpl($db,$registrationId);}
function pgQrPng($token){return qrPngMpl($token);}
function pgSendTicket($db,$config,$payment){if($payment['status']!=='PAID'||$payment['email_confirmacao_em'])return;$q=$db->prepare('SELECT i.numero,p.nome_completo,p.email,c.nome AS categoria_nome,d.distancia_km FROM inscricoes i JOIN participantes p ON p.id=i.participante_id JOIN categorias c ON c.id=i.categoria_id JOIN distancias d ON d.id=i.distancia_id WHERE i.id=?');$q->execute(array($payment['inscricao_id']));$r=$q->fetch();if(!$r)return;$token=pgTicket($db,$payment['inscricao_id']);$png=pgQrPng($token);$boundary='MPL_'.bin2hex(random_bytes(10));$message="Olá, {$r['nome_completo']}!\n\nPagamento confirmado. Seu ingresso da 4ª Corrida MPL está anexado.\nNúmero: {$r['numero']}\nCategoria: {$r['categoria_nome']}\nDistância: {$r['distancia_km']} km\nCódigo: $token";$headers=array('From: 4ª Corrida MPL <'.$config['mail_from'].'>','MIME-Version: 1.0','Content-Type: multipart/mixed; boundary="'.$boundary.'"');$body='--'.$boundary."\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\n".chunk_split(base64_encode($message)).'--'.$boundary."\r\nContent-Type: image/png; name=\"ingresso-corrida-mpl.png\"\r\nContent-Transfer-Encoding: base64\r\nContent-Disposition: attachment; filename=\"ingresso-corrida-mpl.png\"\r\n\r\n".chunk_split(base64_encode($png)).'--'.$boundary."--\r\n";if(filter_var($config['mail_enabled'],FILTER_VALIDATE_BOOLEAN)&&@mail($r['email'],'=?UTF-8?B?'.base64_encode('Pagamento confirmado e ingresso, 4ª Corrida MPL').'?=',$body,implode("\r\n",$headers)))$db->prepare('UPDATE pagamentos_gateway SET email_confirmacao_em=NOW() WHERE id=?')->execute(array($payment['id']));}
function pgApplyOrder($db,$config,$payment,$order){$id=isset($order['id'])?(string)$order['id']:'';if(strpos($id,'or_')!==0||(!empty($order['code'])&&$order['code']!==$payment['referencia_externa']))throw new RuntimeException('Pedido Pagar.me não corresponde à inscrição.');$charge=!empty($order['charges'][0])?$order['charges'][0]:array();$status=pgOrderStatus($order);$amount=isset($charge['paid_amount'])?(int)$charge['paid_amount']:(isset($order['amount'])?(int)$order['amount']:null);if($status==='PAID'&&$amount!==(int)round($payment['valor']*100))throw new RuntimeException('Valor confirmado não corresponde à inscrição.');$method=isset($charge['payment_method'])&&$charge['payment_method']==='pix'?'PIX':(isset($charge['payment_method'])&&$charge['payment_method']==='credit_card'?'CARD':'CHECKOUT');$db->prepare('UPDATE pagamentos_gateway SET metodo=?,order_id=?,status=?,status_gateway=?,confirmado_em=IF(?=\'PAID\',COALESCE(confirmado_em,NOW()),confirmado_em),atualizado_em=NOW() WHERE id=?')->execute(array($method,$id,$status,isset($charge['status'])?$charge['status']:$order['status'],$status,$payment['id']));if($status==='PAID'){$db->prepare("UPDATE inscricoes SET status='paga' WHERE id=? AND status<>'cancelada'")->execute(array($payment['inscricao_id']));$payment=pgLoad($db,$payment['inscricao_id']);pgSendTicket($db,$config,$payment);}return pgLoad($db,$payment['inscricao_id']);}

if(in_array($acao,array('create-checkout','pagarme-payment-status','pagarme-webhook'),true)){pgSchema($db);}
if($acao==='create-checkout'){
    $id=(int)(isset($dados['registration_id'])?$dados['registration_id']:0);$r=paymentOwner($db,$id);if(strtolower((string)$r['tipo'])==='colaborador_mpl'||(float)$r['valor']<=0||in_array($r['status'],array('confirmada','paga'),true))resposta(array('error'=>'Esta inscrição é isenta e não pode gerar cobrança.'),409);$p=pgLoad($db,$id);if($p&&$p['status']==='PAID')resposta(array('payment'=>pgView($p)));if($p&&$p['status']==='PROCESSING'&&$p['payment_link_url']&&strtotime($p['checkout_expira_em'])>time())resposta(array('payment'=>pgView($p)));
    $amount=(int)round($r['valor']*100);$reference=substr('MPL-'.$r['numero'].'-'.strtoupper(bin2hex(random_bytes(4))),0,64);$expires=max(15,min(1440,(int)$config['pagarme_checkout_expires_minutes']));$installments=array();for($i=1;$i<=max(1,min(12,(int)$config['pagarme_max_installments']));$i++)$installments[]=array('number'=>$i,'total'=>$amount);
    $payload=array('is_building'=>false,'name'=>substr('Inscrição '.$r['numero'].' - Corrida MPL',0,64),'order_code'=>$reference,'type'=>'order','expires_in'=>$expires,'max_sessions'=>5,'max_paid_sessions'=>1,'payment_settings'=>array('accepted_payment_methods'=>array('credit_card','pix'),'credit_card_settings'=>array('operation_type'=>'auth_and_capture','installments_setup'=>array('interest_type'=>'simple'),'installments'=>$installments),'pix_settings'=>array('expires_in'=>$expires*60)),'cart_settings'=>array('items'=>array(array('name'=>'Inscrição '.$r['categoria_nome'].' - 4ª Corrida MPL','description'=>'Inscrição #'.$r['numero'],'amount'=>$amount,'default_quantity'=>1))));
    list($http,$body)=pgRequest($config,'POST','/paymentlinks',$payload);if($http<200||$http>=300)resposta(array('error'=>isset($body['message'])?$body['message']:'A Pagar.me recusou o Checkout.'),400);if(empty($body['id'])||empty($body['url'])||!pgCheckoutUrl($body['url']))resposta(array('error'=>'Link de Checkout inválido.'),400);
    if(!$p)$db->prepare("INSERT INTO pagamentos_gateway(inscricao_id,referencia_externa,valor) VALUES(?,?,?)")->execute(array($id,$reference,$r['valor']));else $db->prepare("UPDATE pagamentos_gateway SET referencia_externa=?,valor=?,metodo='CHECKOUT',status='PROCESSING',order_id=NULL,email_confirmacao_em=NULL WHERE id=?")->execute(array($reference,$r['valor'],$p['id']));$p=pgLoad($db,$id);$db->prepare('UPDATE pagamentos_gateway SET payment_link_id=?,payment_link_url=?,checkout_expira_em=?,status_gateway=?,atualizado_em=NOW() WHERE id=?')->execute(array($body['id'],$body['url'],date('Y-m-d H:i:s',time()+$expires*60),isset($body['status'])?$body['status']:'active',$p['id']));resposta(array('payment'=>pgView(pgLoad($db,$id))));
}
if($acao==='pagarme-payment-status'){$id=(int)(isset($dados['registration_id'])?$dados['registration_id']:0);paymentOwner($db,$id);$p=pgLoad($db,$id);if(!$p)resposta(array('error'=>'Nenhum Checkout criado.'),404);if($p['status']==='PROCESSING'){list($http,$body)=pgRequest($config,'GET','/orders?code='.rawurlencode($p['referencia_externa']).'&page=1&size=10');if($http>=200&&$http<300&&!empty($body['data']))foreach($body['data'] as $order)if(isset($order['code'])&&$order['code']===$p['referencia_externa']){$p=pgApplyOrder($db,$config,$p,$order);break;}}resposta(array('payment'=>pgView($p)));}
if($acao==='pagarme-webhook'){$data=isset($dados['data'])&&is_array($dados['data'])?$dados['data']:$dados;$orderId=!empty($data['order']['id'])?$data['order']['id']:(isset($data['id'])?$data['id']:'');if(strpos($orderId,'or_')!==0)resposta(array('ok'=>true,'ignored'=>true));list($http,$order)=pgRequest($config,'GET','/orders/'.rawurlencode($orderId));if($http<200||$http>=300)resposta(array('error'=>'Pedido não confirmado.'),503);$q=$db->prepare('SELECT * FROM pagamentos_gateway WHERE referencia_externa=? OR order_id=? LIMIT 1');$q->execute(array(isset($order['code'])?$order['code']:'',$orderId));$p=$q->fetch();if(!$p)resposta(array('error'=>'Pedido desconhecido.'),404);$p=pgApplyOrder($db,$config,$p,$order);resposta(array('ok'=>true,'status'=>$p['status']));}
